url: https://bhaveshvasnani.github.io
baseurl: /

# Site settings
title: Bhavesh Vasnani
email: bhaveshvasnani197@gmail.com
description: "Bhavesh Vasnani's Personal Webspace"


# Team names, titles and social links
people:
- name: MTA Certification
  pic: 1
  position: Microsoft Certification
  link: https://www.youracclaim.com/badges/459a7267-27e7-48a2-bd49-eb4f9ab675ee
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: stack-overflow
#      url: #

- name: C++ Certification
  pic: 2
  position: TestDome Certification
  link: https://www.testdome.com/cert/as84jk1b65
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: linkedin
#      url: #

- name: Machine Learning
  pic: 3
  position: Coursera (Stanford University) Certification
  link: https://www.coursera.org/account/accomplishments/certificate/5T5QWGKD63G3
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

- name: Setup ELK Stack for Centralized Logging
  pic: 6
  position: Medium Story
  link: https://medium.com/@bhaveshvasnani197/setup-elk-stack-with-filebeat-and-curator-for-logging-in-scala-spring-projects-aa3c03e066af
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

- name: Setup Terraform with Kubernetes Provider
  pic: 7
  position: Medium Story
  link: https://medium.com/@bhaveshvasnani197/how-to-setup-terraform-with-kubernetes-provider-356d0778e771
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

- name: Distributed Programming Concepts in Java
  pic: 5
  position: Coursera (Rice University) Certification
  link: https://www.coursera.org/account/accomplishments/certificate/6XNVMZFANKEN
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

- name: IOS App Development
  pic: 9
  position: Workshop
  link: https://drive.google.com/file/d/0BwxLqymyrm3ZbjhDQzRtaHZNMkE/view
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

- name: Cryptography
  pic: 4
  position: Coursera (University of Maryland) Certification
  link: https://www.coursera.org/account/accomplishments/certificate/DB7ARW6CHQKT
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

- name: Google DevFest
  pic: 8
  position: Hackathon
  link: https://drive.google.com/file/d/1o1HxfcYfUuLU7gzawh_LdGVvRvqBxUrG/view
#  social:
#    - title: twitter
#      url: #
#    - title: facebook
#      url: #
#    - title: google-plus
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/bhavesh-vasnani/
  - title: github
    url: https://github.com/bhaveshvasnani
  - title: facebook 
    url: https://www.facebook.com/bhavesh.vasnani
  - title: instagram
    url: https://www.instagram.com/bhaveshvasnani/

# Postal address (add as many lines as necessary)
address:
  - line: D-36, Swarankar Colony, RPA Road
  - line: Jaipur, Rajasthan, India 302016

# Build settings
markdown: kramdown
permalink: pretty
